export const languagePack = {
    pl: {
        index1: "Kalkulator darowizny w walucie obcej",
        index2: "to narzędzie do szybkiego i łatwego przeliczenia darowizny otrzymanej w walucie obcej na równowartość w złotówkach wraz z wyliczeniem należnego podatku.",
        index3: "Co to jest darowizna?",
        index4: "Art. 888 KC: § 1. Przez umowę darowizny darczyńca zobowiązuje się do bezpłatnego świadczenia na rzecz obdarowanego kosztem swego majątku.",
        index5: "Co należy zrobić, kiedy otrzyma się darowiznę w walucie obcej?",
        index6: "Przeliczyć wartość darowizny po średnim kursie NBP z dnia, w którym ją otrzymaliśmy, sprawdzić, czy należy zapłacic podatek i w jakiej wysokości, a na koniec zgłosić darowiznę na formularzu SD-3 lub SD-Z2 do Urzędu Skarbowego.",
        index7: "Kalkulator wykona za Ciebie niezbędne obliczenia. W menu -> formularze znajdziesz dokumenty do zgłoszenia darowizny ze strony podatki.gov.pl. W menu -> filmy znajdują się krótkie poradniki dot. darowizn przygotowane przez Ministerstwo Finansów.",
        kalkulator1: "Kim jesteś dla darczyńcy? Kliknij w przycisk, aby wybrać odpowiednią grupę podatkową i zobaczyć jej opis.<br>UWAGA! Możesz pominąć ten krok, jeśli nie chcesz liczyć należnego podatku.",
        kalkulator2: "Wybierz datę otrzymania darowizny.",
        kalkulator3: "Wczytywanie...",
        kalkulator4: "Wybierz walutę i wpisz kwotę.",
        kalkulator5: "Czyszczenie formularza",
        kalkulator6: "Czy na pewno chcesz usunąć wszystkie dane na formularzu?",
        kalkulator7: "Nie",
        kalkulator8: "Tak",
        kalkulator9: "WYNIK",
        kalkulator10: "Średnie kursy walut NBP wylicza w każdy dzień roboczy. Ceny walut publikowane są między godziną 11:45 a 12:15. Kalkulator automatycznie wybierze ostatnie opublikowane notowanie."
    },
    en: {
        index1: "Foreign currency donation kalkulator",
        index2: "is a tool for quick and easy conversion of a donation received in a foreign currency into the equivalent in PLN, along with the calculation of the tax due.",
        index3: "What is a donation?",
        index4: "Art. 888 of the Civil Code: § 1. By a donation agreement, the donor undertakes to provide a free benefit to the recipient at the expense of his property.",
        index5: "What should I do when I receive a foreign currency donation?",
        index6: "Calculate the value of the donation at the average exchange rate of the National Bank of Poland on the day we received it, check whether you should pay tax and in what amount, and finally report the donation on the SD-3 or SD-Z2 form to the Tax Office.",
        index7: "The kalkulator will do the necessary calculations for you. In the menu -> forms you will find documents for submitting a donation from the Tax.gov.pl website. In the menu -> videos there are short guides on donations prepared by the Ministry of Finance.",
        kalkulator1: "Who are you to the donor? Click on the button to select the appropriate tax group and see its description.<br>NOTE! You can skip this step if you do not want to calculate the tax due.",
        kalkulator2: "Select the date when you receive your donation.",
        kalkulator3: "Loading...",
        kalkulator4: "Select currency and enter amount.",
        kalkulator5: "Clear form",
        kalkulator6: "Are you sure you want to delete all data on the form?",
        kalkulator7: "No",
        kalkulator8: "Yes",
        kalkulator9: "RESULT",
        kalkulator10: "NBP calculates average exchange rates every working day. Currency prices are published between 11:45 and 12:15. The kalkulator will automatically select the last published quotation."
    },
};