export const languagePack = {pl: {mySidenav1: "główna",
        mySidenav2: "kalkulator",
        mySidenav3: "formularze",
        mySidenav4: "filmy",
        index1: "Kalkulator darowizny w walucie obcej",
        index2: "to narzędzie do szybkiego i łatwego przeliczenia darowizny otrzymanej w walucie obcej na równowartość w złotówkach wraz z wyliczeniem należnego podatku.",
        index3: "Co to jest darowizna?",
        index4: "Art. 888 KC: § 1. Przez umowę darowizny darczyńca zobowiązuje się do bezpłatnego świadczenia na rzecz obdarowanego kosztem swego majątku.",
        index5: "Co należy zrobić, kiedy otrzyma się darowiznę w walucie obcej?",
        index6: "Przeliczyć wartość darowizny po średnim kursie NBP z dnia, w którym ją otrzymaliśmy, sprawdzić, czy należy zapłacic podatek i w jakiej wysokości, a na koniec zgłosić darowiznę na formularzu SD-3 lub SD-Z2 do Urzędu Skarbowego.",
        index7: "Kalkulator wykona za Ciebie niezbędne obliczenia. W menu -> formularze znajdziesz dokumenty do zgłoszenia darowizny ze strony podatki.gov.pl. W menu -> filmy znajdują się krótkie poradniki dot. darowizn przygotowane przez Ministerstwo Finansów.",
        index8: "Kalkulator",
        kalkulator1: "Kim jesteś dla darczyńcy? Kliknij w przycisk, aby wybrać odpowiednią grupę podatkową i zobaczyć jej opis.<br>UWAGA! Możesz pominąć ten krok, jeśli nie chcesz liczyć należnego podatku.",
        kalkulator2: "Wybierz datę otrzymania darowizny.",
        kalkulator3: "Wczytywanie...",
        kalkulator4: "Wybierz walutę i wpisz kwotę.",
        kalkulator5: "Czyszczenie formularza",
        kalkulator6: "Czy na pewno chcesz usunąć wszystkie dane na formularzu?",
        kalkulator7: "Nie",
        kalkulator8: "Tak",
        kalkulator9: "WYNIK",
        kalkulator10: "Średnie kursy walut NBP wylicza w każdy dzień roboczy. Ceny walut publikowane są między godziną 11:45 a 12:15. Kalkulator automatycznie wybierze ostatnie opublikowane notowanie.",
        groupSelect1: "Kim jesteś dla darczyńcy? Kliknij w przycisk, aby zobaczyć opis i wybrać odpowiednią grupę podatkową.<br>UWAGA! Możesz pominąć ten krok, jeśli nie chcesz liczyć należnego podatku.",
        groupSelect2: 'Tzw. "0" grupa podatkowa, czyli najbliższa rodzina: małżonek, wstępni (rodzice, dziadkowie, pradziadkowie), zstępni (dzieci, wnuki, prawnuki), pasierb, ojczym, macocha, rodzeństwo. UWAGA: Jeżeli nie zgłosisz spadku w ciągu 6 miesięcy, wówczas zapłacisz podatek na zasadach określonych dla I grupy podatkowej!',
        groupSelect3: "I grupa podatkowa: małżonek, wstępni (rodzice, dziadkowie, pradziadkowie), zstępni (dzieci, wnuki, prawnuki), pasierb, ojczym, macocha, rodzeństwo, teściowie, zięć, synowa",
        groupSelect4: "II grupa podatkowa: zstępni rodzeństwa (np. dzieci siostry, wnuki brata), rodzeństwo rodziców (np. ciotki, wujowie), zstępni i małżonkowie pasierbów, małżonkowie rodzeństwa i rodzeństwo małżonków, małżonkowie rodzeństwa małżonków, małżonkowie innych zstępnych (np. mąż wnuczki)",
        groupSelect5: "III grupa podatkowa: pozostali nabywcy.",
        appNotowanie: "Notowanie",
        appKurs: "Kurs",
        appDarowizna: "Darowizna",
        appPodatek: "Podatek",
        appErrorCalendar: "WYBIERZ DATĘ",
        appErrorCurSum: "WPROWADŹ WARTOŚĆ",
        appErrorCurrencyMenu: "WYBIERZ WALUTĘ",
        countTaxZero1: "Darowizna przekracza 10434zł. Na zgłoszenie darowizny do US masz pół roku od daty jej przyjęcia. Formularz SD-Z2.",
        countTaxZero2: "Nie musisz zgłaszać darowizny, jesli suma darowizn od jednego darczyńcy nie przekroczyła 10 434zł w ciągu 5 lat poprzedzających rok, w którym nastąpiła ostatnia darowizna.",
        countTaxOne1: "Nie musisz zgłaszać darowizny, jesli suma darowizn od jednego darczyńcy nie przekroczyła 10 434 zł w ciągu 5 lat poprzedzających rok, w którym nastąpiła ostatnia darowizna.",
        countTaxOne2: "Podatek to 3%. Na zgłoszenie darowizny do US masz miesiąc od daty jej przyjęcia. Formularz SD-3.",
        countTaxOne3: "Podatek to 333 zł 90 gr i 5% od nadwyżki ponad 11 128 zł. Na zgłoszenie darowizny do US masz miesiąc od daty jej przyjęcia. Formularz SD-3.",
        countTaxOne4: "Podatek to 890 zł 30 gr i 7% od nadwyżki ponad 22 256 zł. Na zgłoszenie darowizny do US masz miesiąc od daty jej przyjęcia. Formularz SD-3.",
        countTaxTwo1: "Nie musisz zgłaszać darowizny, jesli suma darowizn od jednego darczyńcy nie przekroczyła 7 878 zł w ciągu 5 lat poprzedzających rok, w którym nastąpiła ostatnia darowizna.",
        countTaxTwo2: "Podatek to 7%. Na zgłoszenie darowizny do US masz miesiąc od daty jej przyjęcia. Formularz SD-3.",
        countTaxTwo3: "Podatek to 779 zł 00 gr i 9% od nadwyżki ponad 11 128 zł. Na zgłoszenie darowizny do US masz miesiąc od daty jej przyjęcia. Formularz SD-3.",
        countTaxTwo4: "Podatek to 1780 zł 60 gr i 12% od nadwyżki ponad 22 256 zł. Na zgłoszenie darowizny do US masz miesiąc od daty jej przyjęcia. Formularz SD-3.",
        countTaxThree1: "Nie musisz zgłaszać darowizny, jesli suma darowizn od jednego darczyńcy nie przekroczyła 5 308 zł w ciągu 5 lat poprzedzających rok, w którym nastąpiła ostatnia darowizna.",
        countTaxThree2: "Podatek to 12%. Na zgłoszenie darowizny do US masz miesiąc od daty jej przyjęcia. Formularz SD-3.",
        countTaxThree3: "Podatek to 1335 zł 40 gr i 16% od nadwyżki ponad 11 128 zł. Na zgłoszenie darowizny do US masz miesiąc od daty jej przyjęcia. Formularz SD-3.",
        countTaxThree4: "Podatek to 3115 zł 90 gr i 20% od nadwyżki ponad 22 256 zł. Na zgłoszenie darowizny do US masz miesiąc od daty jej przyjęcia. Formularz SD-3.",
        countTaxInfo1: "brak danych",
        countTaxInfo2: "Nie wybrano grupy podatkowej.",
        formularzeOne1: "Formularz SD-Z2",
        formularzeOne2: "Zgłoszenie o nabyciu własności rzeczy lub praw majątkowych",
        formularzeTwo1: "Formularz SD-3",
        formularzeTwo2: "Zeznanie podatkowe o nabyciu rzeczy lub praw majątkowych",
        formularzeThree1: "Załącznik SD-3A",
        formularzeThree2: "Załącznik do deklaracji SD-3 -&nbsp;inf. o pozostałych podatnikach",
        formularzeOpen: "Otwórz",
        formularzeInfo: "Więcej informacji na stronie:",
        filmy1: "OBOWIĄZKI PODATNIKA",
        filmy2: "FORMULARZ SD-Z2",
        filmy3: "FORMULARZ SD-3"}, 
        en: {mySidenav1: "main",
        mySidenav2: "calculator",
        mySidenav3: "forms",
        mySidenav4: "movies",
        index1: "Foreign currency donation calculator",
        index2: "is a tool for quick and easy conversion of a donation received in a foreign currency into the equivalent in PLN, along with the calculation of the tax due.",
        index3: "What is a donation?",
        index4: "Art. 888 of the Civil Code: § 1. By a donation agreement, the donor undertakes to provide a free benefit to the recipient at the expense of his property.",
        index5: "What should I do when I receive a foreign currency donation?",
        index6: "Calculate the value of the donation at the average exchange rate of the National Bank of Poland on the day we received it, check whether you should pay tax and in what amount, and finally report the donation on the SD-3 or SD-Z2 form to the Tax Office.",
        index7: "The calculator will do the necessary calculations for you. In the menu -> forms you will find documents for submitting a donation from the podatki.gov.pl website. In the menu -> videos there are short guides on donations prepared by the Ministry of Finance.",
        index8: "Calculator",
        kalkulator1: "Who are you to the donor? Click on the button to select the appropriate tax group and see its description.<br>NOTE! You can skip this step if you do not want to calculate the tax due.",
        kalkulator2: "Select the date when you receive your donation.",
        kalkulator3: "Loading...",
        kalkulator4: "Select currency and enter amount.",
        kalkulator5: "Clear form",
        kalkulator6: "Are you sure you want to delete all data on the form?",
        kalkulator7: "No",
        kalkulator8: "Yes",
        kalkulator9: "RESULT",
        kalkulator10: "NBP calculates average exchange rates every working day. Currency prices are published between 11:45 and 12:15. The calculator will automatically select the last published quotation.",
        groupSelect1: "Who are you to the donor? Click the button to see the description and select the appropriate tax group.<br>NOTE! You can skip this step if you do not want to count the tax due.",
        groupSelect2: 'So-called "0" tax group, i.e. immediate family: spouse, ascendants (parents, grandparents, great-grandparents), descendants (children, grandchildren, great-grandchildren), stepson, stepfather, stepmother, siblings. ATTENTION: If you do not report the inheritance within 6 months, then you will pay the tax on the terms specified for the 1st tax group!',
        groupSelect3: "I tax group: spouse, ascendants (parents, grandparents, great-grandparents), descendants (children, grandchildren, great-grandchildren), stepson, stepfather, stepmother, siblings, in-laws, son-in-law, daughter-in-law",
        groupSelect4: "II tax group: descendants of siblings (e.g. sister's children, grandchildren of brother), parents' siblings (e.g. aunts, uncles), descendants and stepchildren's spouses, siblings' spouses and spouses' siblings, spouses of spouses' siblings, spouses of other descendants (e.g. granddaughter's husband)",
        groupSelect5: "Third tax group: other buyers.",
        appNotowanie: "Record",
        appKurs: "Rate",
        appDarowizna: "Donation",
        appPodatek: "Tax",
        appErrorCalendar: "SELECT DATE",
        appErrorCurSum: "ENTER VALUE",
        appErrorCurrencyMenu: "CHOOSE CURRENCY",
        countTaxZero1: "The donation exceeds PLN 10,434. You have six months from the date of receipt to submit a donation to the Tax Office. Form SD-Z2.",
        countTaxZero2: "You don't have to report a donation if the sum of donations from one donor did not exceed PLN 10,434 in the 5 years preceding the year in which the last donation was made.",
        countTaxOne1: "You don't need to report a donation if the sum of donations from one donor did not exceed PLN 10,434 in the 5 years preceding the year in which the last donation was made.",
        countTaxOne2: "The tax is 3%. You have one month from the date of receipt to submit your donation to the Tax Office. Form SD-3.",
        countTaxOne3: "The tax is PLN 333.90 and 5% on the surplus over PLN 11,128. You have one month from the date of receipt to submit your donation to the Tax Office. Form SD-3.",
        countTaxOne4: "The tax is PLN 890.30 and 7% on the surplus over PLN 22,256. You have one month from the date of receipt to submit a donation to the Tax Office. Form SD-3.",
        countTaxTwo1: "You don't have to report a donation if the sum of donations from one donor did not exceed PLN 7,878 in the 5 years preceding the year in which the last donation was made.",
        countTaxTwo2: "Tax is 7%. You have one month from the date of receipt to report your donation to the Tax Office. Form SD-3.",
        countTaxTwo3: "The tax is PLN 779 00 gr and 9% on the surplus over PLN 11,128. You have one month from the date of receipt to submit your donation to the Tax Office. Form SD-3.",
        countTaxTwo4: "The tax is PLN 1,780.60 and 12% on the surplus over PLN 22,256. You have one month from the date of receipt to submit your donation to the Tax Office. Form SD-3.",
        countTaxThree1: "You don't need to report a donation if the sum of donations from one donor did not exceed PLN 5,308 in the 5 years preceding the year in which the last donation was made.",
        countTaxThree2: "The tax is 12%. You have one month from the date of receipt to submit your donation to the Tax Office. Form SD-3.",
        countTaxThree3: "The tax is PLN 1,335.40 and 16% on the surplus over PLN 11,128. You have one month from the date of receipt to submit your donation to the Tax Office. Form SD-3.",
        countTaxThree4: "The tax is PLN 3,115.90 and 20% on the surplus over PLN 22,256. You have one month from the date of receipt to submit a donation to the Tax Office. Form SD-3.",
        countTaxInfo1: "no data",
        countTaxInfo2: "No tax group selected.",
        formularzeOne1: "Form SD-Z2",
        formularzeOne2: "Notification on the acquisition of ownership of things or property rights",
        formularzeTwo1: "Form SD-3",
        formularzeTwo2: "Tax return on the acquisition of property or property rights",
        formularzeThree1: "Appendix SD-3A",
        formularzeThree2: "Appendix to the SD-3 declaration -&nbsp;info on other taxpayers",
        formularzeOpen: "Open",
        formularzeInfo: "For more information visit:",
        filmy1: "TAXPAYER'S OBLIGATIONS",
        filmy2: "FORM SD-Z2",
        filmy3: "FORM SD-3"}};